### ISSUE TITLE
Feature Request: Add Wekan to DockerBunker

### ISSUE THREAD

**Issue by xet7** [chaosbunker/dockerbunker#1]
Hi, I saw your comment [at Hacker News](https://news.ycombinator.com/item?id=17006797). Can you add Wekan to DockerBunker? I added DockerBunker to Wekan [Platforms](https://github.com/wekan/wekan/wiki/Platforms#docker), [Backups](https://github.com/wekan/wekan/wiki/Export-Docker-Mongo-Data) and [Docker links](https://github.com/wekan/wekan/wiki/Docker) pages. [Wekan website here](https://wekan.github.io).

BR,
xet7
Maintainer of Wekan

**Comment by chaosbunker** [comment]
Sure, thanks!

i’ll add Wekan as soon as I have some spare time and will let you know here.

**Comment by chaosbunker** [comment]
Hi @xet7, I have just added Wekan. Let me know if there is anything I can improve:-)
