### ISSUE TITLE
gitea config issue

### ISSUE THREAD

**Issue by stephanfriedrich** [chaosbunker/dockerbunker#12]
hi thx for your awesome work.

i got an issue after start configuration for gitea. 

```
dockerbunker/data/services/gitea/gitea.sh: Zeile 44: ${GITEA_ADMIN }: Falsche Variablenersetzung.
```

**GNU bash, Version 4.4.20(1)**
**mint 5.2.15-050215-generic**

**Comment by chaosbunker** [comment]
It was due to a typo. Thanks for catching this! :-)
