### ISSUE TITLE
gogs and drone

### ISSUE THREAD

**Issue by stephanfriedrich** [chaosbunker/dockerbunker#15]

**Comment by stephanfriedrich** [comment]
Hi,
i tried to install gogs (workls like a charm) with droneCI. drone Ci will be installed without issues but after if i try to login via drone i got an nginx issue.

```
2019/11/03 14:33:14 [error] 6#6: *106 upstream timed out (110: Operation timed out) while reading response header from upstream, client: fuuu, server: drone.my.domain, request: "POST /login HTTP/1.1", upstream: "http://172.20.0.6:80/login", host: "drone.my.domain", referrer: "https://drone.my.domain/login/form"
```

Do you have any advice ? greetings

**Comment by chaosbunker** [comment]
Sorry I couldn't reproduce this. I just tested this on a fresh ubuntu system with a non-root user running docker and installed gogs and drone ci via dockerbunker. Everything worked as it should and I could log into drone and sync my gogs repos.
