### ISSUE TITLE
backup permission

### ISSUE THREAD

**Issue by stephanfriedrich** [chaosbunker/dockerbunker#17]
hi, i run my docker with user: docker. and everythink works ... 
but with your backup procedure, it throws an premission issue because it use root-previleges.

i got that issue: 
```
→ Backup Service

Compressing volumes
- gitea-data-vol-1 ✔
- gitea-db-vol-1 ✔
mkdir: cannot create directory ‘/www/dockerbunker/data/backup/gitea/20191103_1445/ssl’: Permission denied
```

in my case within dockerbunker/data/backup/gitea/
```
drwxr-xr-x 2 root   root   4096 Nov  3 14:47 20191103_1445
```

**Comment by chaosbunker** [comment]
Please delete already created backup directories or run `chown -R youruser:yourgroup` on `data/backup` and then re-try the backup.
