### ISSUE TITLE
Upgrading dockerbunker

### ISSUE THREAD

**Issue by Teenspirit** [chaosbunker/dockerbunker#18]
Hi,

Should preface that this is not an issue, but rather my inexperience.

How do I upgrade dockerbunker? When I try to do a gitclone, it returns saying that the folder is not empty. I dont want to lose the configurations for the services im currently running. Are the variables saved in a different folder? Any help would be greatly appreciated. 

Regards,
Teenspirit

**Comment by Teenspirit** [comment]
Also want to add that when I tried to upgrade my Nextcloud image before, something got messed up and my Nextcloud got corrupted. Had to remove the whole thing and start over again, reuploading 50gb worth of data :(

**Comment by chaosbunker** [comment]
Hi @Teenspirit 

you would just have to do `git pull`. Please have a look in the git documentation for details.

Regarding Nextcloud..this was due to a wrong volume name (see [fix](https://github.com/chaosbunker/dockerbunker/commit/15ae7b767bf01f30abbd619566dc819f01cefaa1))
