### ISSUE TITLE
Using Script on Atomic Hosts

### ISSUE THREAD

**Issue by BzowK** [chaosbunker/dockerbunker#2]
Good Morning - 

I found your project earlier this morning when looking for a simple method of adding python-based web hosted apps in Docker.  I thought I'd give it a go, so performed the following steps:

1. SSH'd into my Docker host (Project Atomic Fedora 27 which already runs ~8 containers)
2. Executed "git clone https://github.com/chaosbunker/dockerbunker.git && cd dockerbunker"
3. Executed "./dockerbunker.sh"

I then immediately get a message saying that it couldn't find docker and provides a wget command to install it.  I obviously already have Docker installed so looked at the script to see how it checked and saw it looks to see if docker is installed using dpkg which is a package not installed on atomic hosts.  

I removed lines 3-7 to bypass the check then ran the script and got the menu.  I didn't see an option to add a Python-based site, so thought I'd just try a static HTML one so selected #1.  Unfortunately, I then got the error:

> ...
> > 25) Destroy everything
> 26) Exit
> #? 1
> 
> → Checking service status
> 
> ls: cannot access '/root/dockerbunker/data/env/static': No such file or directory
> 
> Static HTML Site
> 1) Configure Service
> 2) Exit
> #? 2
> ...

root is the default use for Atomic and the beginning of that path does exist, but looking at a list of the contents of the "env" folder, there's only a file in it.

> [root@kndockerhost env]# ls
> dockerbunker.env

Ohh well, just wanted to report my experience.  Hopefully I can find something that will easily allow me to add my sites with reverse proxy or can play with your script more in the future.

Thanks!

**Comment by chaosbunker** [comment]
Hey @BzowK,

Thanks for reporting this! I have developed this on debian, I guess I should have mentioned that somewhere in the README :-) Never tested on other systems..

I have just made some (minor) changes to check for presence of docker under Fedora, as well as centOS and RHEL and also fixed the error of not finding the directory.

Please let me know if any other changes have to be made to make it work for you on fedora...
