### ISSUE TITLE
Add MIT License?

### ISSUE THREAD

**Issue by xet7** [chaosbunker/dockerbunker#5]
Hi,
without added license textfile this code is propietary.

Can you add MIT License, like DPlatform this is based? Wekan an Rocket.Chat also has MIT License.

**Comment by chaosbunker** [comment]
Not adding a license was an oversight on my part, thanks for pointing it out! I have just added a license.

Btw, DPlatform just gave me the idea to make dockerbunker. My code is not based on it:-)
