### ISSUE TITLE
Wekan and ROOT_URL

### ISSUE THREAD

**Issue by Phaiax** [chaosbunker/dockerbunker#9]
Hello

I had two issues with my wekan installation.

First was that nginx failed to install at first, because the default nginx in my debian already blocked port 80. This messed up the docker images somehow, I had to explicitly delete the nginx docker container before being able to successfully destroy-setup wekan again. (I don't know the exact error message anymore, but it something like "nginx container already exists")

Second, the ROOT_URL in wekan is set to http://localhost

When opening the wekan interface everything works fine at first. But when clicking a card, the page reloads and changes the url to the one given by ROOT_URL. If I use wekan from another PC, the url in the browser changes to http://localhost/foobarxyz and can not be found.

I fixed this by manually changing the ROOT_URL item in data/services/wekan/wekan.sh and reinstalling. (For some reason changing ROOT_URL in data/env/wekan.sh did not work, but that may be ok and the real reason is that I do not really understand how docker works)

Anyway, thanks for dockerbunker. Installing was really a breeze especially because mongodb was automatically installed. (The Database is part of the backup, correct?)

**Comment by drodewyk** [comment]
Hi there:-)

Thanks for pointing at the ROOT_URL issue. I fixed this and it should now point to the correct URL when clicking a card..even after reinstalling.

Regarding your nginx issue .. are you using your default nginx for something? If not I would just stop it (`service nginx stop`) and use the dockerbunker nginx container. Or maybe you can integrate whatever you are doing with your default nginx into dockebrunker? integrating other stuff is fairly simple..i just wish I had documented that 🙈 

If you want to use your default nginx container you will have to remove the nginx-dockerbunker container and make sure that your nginx picks up the nginx configuration file for wekan (data/conf/nginx/conf.d/yourwekanurl.com.conf) and the certificate etc..

I wouldn't recommend that though, as dockerbunker is made to use the nginx container it comes with.

Regarding backups...yes, all container volumes are part of the backup. If I was you I would make a backup, destroy wekan and restore from the backup to test if it works for you with your default nginx. Might be a bit inconvenient, though, with your setup.

**Comment by Phaiax** [comment]
resolved, thanks.
I am using the nginx-dockerbunker container now
